apiVersion: v1
kind: Service
metadata:
  name: sct-django-k8s-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: sct-django-k8s-deployment